import { TestDefinitions } from "./testDefinition";


export const JSONTests: TestDefinitions = {
    "empty": {
        text: '',
        events: [
            ["parsererror", "expected the schema start (!) or root value"],
            ["end", undefined],
        ],
    },
    "just a string": {
        text: '"a string"',
        testForLocation: true,
        events: [
            ["quotedstring", "a string", [1, 1, 1, 11]],
            ["end", [1, 11]],
        ],
    },
    "unterminated string": {
        text: '"an unterminated string',
        testForLocation: true,
        events: [
            ["tokenizererror", "unterminated string"],
            ["quotedstring", "an unterminated string", [1, 1, 1, 24]],
            ["end", [1, 24]],
        ],
    },
    "newline": {
        text: '\n  "a string"',
        skipRoundTripCheck: true,
        testForLocation: true,
        events: [
            ["quotedstring", "a string", [2, 3, 2, 13]],
            ["end", [2, 13]],
        ],
    },
    "just a number": {
        text: '42',
        testForLocation: true,
        events: [
            ["unquotedtoken", "42", [1, 1, 1, 3]],
            ["end", [1, 3]],
        ],
    },
    "invalid number": {
        text: '42x',
        events: [
            ["validationerror", "Invalid number, unexpected character x in '42x'"],
            ["unquotedtoken", "42x", undefined],
            ["end", undefined],
        ],
    },
    "empty array": {
        text: '[]',
        testForLocation: true,
        events: [
            ["openarray", "[", [1, 1, 1, 2]],
            ["closearray", "]", [1, 2, 1, 3]],
            ["end", [1, 3]],
        ],
    },
    "just slash": {
        text: '["\\\\"]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", "\\", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "zero byte": {
        text: '{"foo": "\\u0000"}',
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["quotedstring", "\u0000", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "empty value": {
        text: '{"foo": ""}',
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["quotedstring", "", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "empty key": {
        text: '{"foo": "bar", "": "baz"}',
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["quotedstring", "bar", undefined],
            ["key", "", undefined],
            ["quotedstring", "baz", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "three byte utf8": {
        text: '{"matzue": "松江", "asakusa": "浅草"}',
        events: [
            ["openobject", "{", undefined],
            ["key", "matzue", undefined],
            ["quotedstring", "松江", undefined],
            ["key", "asakusa", undefined],
            ["quotedstring", "浅草", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "four byte utf8": {
        text: '{ "U+10ABCD": "������" }',
        events: [
            ["openobject", "{", undefined],
            ["key", "U+10ABCD", undefined],
            ["quotedstring", "������", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "bulgarian": {
        text: '["Да Му Еба Майката"]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", "Да Му Еба Майката", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "codepoints from unicodes": {
        text: '["\\u004d\\u0430\\u4e8c\\ud800\\udf02"]',
        skipRoundTripCheck: true,
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", "\u004d\u0430\u4e8c\ud800\udf02", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "empty object": {
        text: '{}',
        events: [
            ["openobject", "{", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "missing property value": {
        text: '{ "foo" }',
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["parsererror", "missing property value"],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "foobar": {
        text: '{"foo": "bar"}',
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["quotedstring", "bar", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "as is": {
        text: "{\"foo\": \"its \\\"as is\\\", \\\"yeah\", \"bar\": false}",
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["quotedstring", 'its "as is", "yeah', undefined],
            ["key", "bar", undefined],
            ["unquotedtoken", "false", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "array": {
        text: '["one", "two"]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", 'one', undefined],
            ["quotedstring", 'two', undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "array fu": {
        text: '["foo", "bar", "baz",true,false,null,{"key":"quotedstring"},' +
            '[null,null,null,[]]," \\\\ "]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", 'foo', undefined],
            ["quotedstring", 'bar', undefined],
            ["quotedstring", 'baz', undefined],
            ["unquotedtoken", "true", undefined],
            ["unquotedtoken", "false", undefined],
            ["unquotedtoken", "null", undefined],
            ["openobject", "{", undefined],
            ["key", 'key', undefined],
            ["quotedstring", "quotedstring", undefined],
            ["closeobject", "}", undefined],
            ["openarray", "[", undefined],
            ["unquotedtoken", "null", undefined],
            ["unquotedtoken", "null", undefined],
            ["unquotedtoken", "null", undefined],
            ["openarray", "[", undefined],
            ["closearray", "]", undefined],
            ["closearray", "]", undefined],
            ["quotedstring", " \\ ", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "simple exp": {
        text: '[10e-01]',
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "10e-01", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "nested": {
        text: '{"a":{"b":"c"}}',
        events: [
            ["openobject", "{", undefined],
            ["key", "a", undefined],
            ["openobject", "{", undefined],
            ["key", "b", undefined],
            ["quotedstring", "c", undefined],
            ["closeobject", "}", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "nested array": {
        text: '{"a":["b", "c"]}',
        events: [
            ["openobject", "{", undefined],
            ["key", "a", undefined],
            ["openarray", "[", undefined],
            ["quotedstring", 'b', undefined],
            ["quotedstring", 'c', undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "array of objs": {
        text: '[{"a":"b"}, {"c":"d"}]',
        events: [
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "a", undefined],
            ["quotedstring", 'b', undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "c", undefined],
            ["quotedstring", 'd', undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "two keys": {
        text: '{"a": "b", "c": "d"}',
        events: [
            ["openobject", "{", undefined],
            ["key", "a", undefined],
            ["quotedstring", "b", undefined],
            ["key", "c", undefined],
            ["quotedstring", "d", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "key true": {
        text: '{"foo": true, "bar": false, "baz": null}',
        testForLocation: true,
        events: [
            ["openobject", "{", [1, 1, 1, 2]],
            ["key", "foo", [1, 2, 1, 7]],
            ["unquotedtoken", "true", [1, 9, 1, 13]],
            ["key", "bar", [1, 15, 1, 20]],
            ["unquotedtoken", "false", [1, 22, 1, 27]],
            ["key", "baz", [1, 29, 1, 34]],
            ["unquotedtoken", "null", [1, 36, 1, 40]],
            ["closeobject", "}", [1, 40, 1, 41]],
            ["end", [1, 41]],
        ],
    },
    "obj strange strings": {
        text: '{"foo": "bar and all\\\"", "bar": "its \\\"nice\\\""}',
        events: [
            ["openobject", "{", undefined],
            ["key", "foo", undefined],
            ["quotedstring", 'bar and all"', undefined],
            ["key", "bar", undefined],
            ["quotedstring", 'its "nice"', undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "bad foo bar": {
        text: '["foo", "bar"',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", 'foo', undefined],
            ["quotedstring", 'bar', undefined],
            ['parsererror', 'unexpected end of document, still in nested type'],
            ["end", undefined],
        ],
    },
    "string invalid escape": {
        text: '["and you can\'t escape thi\s"]',
        testForLocation: true,
        events: [
            ["openarray", "[", [1, 1, 1, 2]],
            ["quotedstring", 'and you can\'t escape this', [1, 2, 1, 29]],
            ["closearray", "]", [1, 29, 1, 30]],
            ["end", [1, 30]],
        ],
    },
    "nuts and bolts": {
        text: '{"boolean, true": true' +
            ', "boolean, false": false' +
            ', "null": null }',
        events: [
            ["openobject", "{", undefined],
            ["key", "boolean, true", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "boolean, false", undefined],
            ["unquotedtoken", "false", undefined],
            ["key", "null", undefined],
            ["unquotedtoken", "null", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "frekin string": {
        text: '["\\\\\\"\\"a\\""]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", '\\\"\"a\"', undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "array of string insanity": {
        text: '["\\\"and this string has an escape at the beginning",' +
            '"and this string has no escapes"]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", "\"and this string has an escape at the beginning", undefined],
            ["quotedstring", "and this string has no escapes", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "non utf8": {
        text: '{"CoreletAPIVersion":2,"CoreletType":"standalone",' +
            '"documentation":"A corelet that provides the capability to upload' +
            ' a folder’s contents into a user’s locker.","functions":[' +
            '{"documentation":"Displays a dialog box that allows user to ' +
            'select a folder on the local system.","name":' +
            '"ShowBrowseDialog","parameters":[{"documentation":"The ' +
            'callback function for results.","name":"callback","required":' +
            'true,"type":"callback"}]},{"documentation":"Uploads all mp3 files' +
            ' in the folder provided.","name":"UploadFolder","parameters":' +
            '[{"documentation":"The path to upload mp3 files from."' +
            ',"name":"path","required":true,"type":"string"},{"documentation":' +
            ' "The callback function for progress.","name":"callback",' +
            '"required":true,"type":"callback"}]},{"documentation":"Returns' +
            ' the server name to the current locker service.",' +
            '"name":"GetLockerService","parameters":[]},{"documentation":' +
            '"Changes the name of the locker service.","name":"SetLockerSer' +
            'vice","parameters":[{"documentation":"The value of the locker' +
            ' service to set active.","name":"LockerService","required":true' +
            ',"type":"string"}]},{"documentation":"Downloads locker files to' +
            ' the suggested folder.","name":"DownloadFile","parameters":[{"' +
            'documentation":"The origin path of the locker file.",' +
            '"name":"path","required":true,"type":"string"},{"documentation"' +
            ':"The Window destination path of the locker file.",' +
            '"name":"destination","required":true,"type":"integer"},{"docum' +
            'entation":"The callback function for progress.","name":' +
            '"callback","required":true,"type":"callback"}]}],' +
            '"name":"LockerUploader","version":{"major":0,' +
            '"micro":1,"minor":0},"versionString":"0.0.1"}',
        events: [
            ["openobject", "{", undefined],
            ["key", "CoreletAPIVersion", undefined],
            ["unquotedtoken", "2", undefined],
            ["key", "CoreletType", undefined],
            ["quotedstring", "standalone", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "A corelet that provides the capability to upload a folder’s contents into a user’s locker.", undefined],
            ["key", "functions", undefined],
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "Displays a dialog box that allows user to select a folder on the local system.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "ShowBrowseDialog", undefined],
            ["key", "parameters", undefined],
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The callback function for results.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "callback", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "callback", undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "Uploads all mp3 files in the folder provided.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "UploadFolder", undefined],
            ["key", "parameters", undefined],
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The path to upload mp3 files from.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "path", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "string", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The callback function for progress.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "callback", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "callback", undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "Returns the server name to the current locker service.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "GetLockerService", undefined],
            ["key", "parameters", undefined],
            ["openarray", "[", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "Changes the name of the locker service.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "SetLockerService", undefined],
            ["key", "parameters", undefined],
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The value of the locker service to set active.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "LockerService", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "string", undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "Downloads locker files to the suggested folder.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "DownloadFile", undefined],
            ["key", "parameters", undefined],
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The origin path of the locker file.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "path", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "string", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The Window destination path of the locker file.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "destination", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "integer", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "documentation", undefined],
            ["quotedstring", "The callback function for progress.", undefined],
            ["key", "name", undefined],
            ["quotedstring", "callback", undefined],
            ["key", "required", undefined],
            ["unquotedtoken", "true", undefined],
            ["key", "type", undefined],
            ["quotedstring", "callback", undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["key", "name", undefined],
            ["quotedstring", "LockerUploader", undefined],
            ["key", "version", undefined],
            ["openobject", "{", undefined],
            ["key", "major", undefined],
            ["unquotedtoken", "0", undefined],
            ["key", "micro", undefined],
            ["unquotedtoken", "1", undefined],
            ["key", "minor", undefined],
            ["unquotedtoken", "0", undefined],
            ["closeobject", "}", undefined],
            ["key", "versionString", undefined],
            ["quotedstring", "0.0.1", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "array of arrays": {
        text: '[[[["foo"]]]]',
        events: [
            ["openarray", "[", undefined],
            ["openarray", "[", undefined],
            ["openarray", "[", undefined],
            ["openarray", "[", undefined],
            ["quotedstring", "foo", undefined],
            ["closearray", "]", undefined],
            ["closearray", "]", undefined],
            ["closearray", "]", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "low overflow": {
        text: '[-9223372036854775808]',
        chunks: [
            '[-92233720',
            '36854775808]',
        ],
        testForLocation: true,
        events: [
            ["openarray", "[", [1, 1, 1, 2]],
            ["unquotedtoken", "-9223372036854775808", [1, 2, 1, 22]],
            ["closearray", "]", [1, 22, 1, 23]],
            ["end", [1, 23]],
        ],
    },
    "high overflow": {
        text: '[9223372036854775808]',
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "9223372036854775808", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "floats": {
        text: '[0.1e2, 1e1, 3.141569, 10000000000000e-10]',
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "0.1e2", undefined],
            ["unquotedtoken", "1e1", undefined],
            ["unquotedtoken", "3.141569", undefined],
            ["unquotedtoken", "10000000000000e-10", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "numbers game": {
        text: '[1,0,-1,-0.3,0.3,1343.32,3345,3.1e124,' +
            ' 9223372036854775807,-9223372036854775807,0.1e2, ' +
            '1e1, 3.141569, 10000000000000e-10,' +
            '0.00011999999999999999, 6E-06, 6E-06, 1E-06, 1E-06,' +
            '"2009-10-20@20:38:21.539575", 9223372036854775808,' +
            '123456789,-123456789,' +
            '2147483647, -2147483647]',
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "1", undefined],
            ["unquotedtoken", "0", undefined],
            ["unquotedtoken", "-1", undefined],
            ["unquotedtoken", "-0.3", undefined],
            ["unquotedtoken", "0.3", undefined],
            ["unquotedtoken", "1343.32", undefined],
            ["unquotedtoken", "3345", undefined],
            ["unquotedtoken", "3.1e124", undefined],
            ["unquotedtoken", "9223372036854775807", undefined],
            ["unquotedtoken", "-9223372036854775807", undefined],
            ["unquotedtoken", "0.1e2", undefined],
            ["unquotedtoken", "1e1", undefined],
            ["unquotedtoken", "3.141569", undefined],
            ["unquotedtoken", "10000000000000e-10", undefined],
            ["unquotedtoken", "0.00011999999999999999", undefined],
            ["unquotedtoken", "6E-06", undefined],
            ["unquotedtoken", "6E-06", undefined],
            ["unquotedtoken", "1E-06", undefined],
            ["unquotedtoken", "1E-06", undefined],
            ["quotedstring", "2009-10-20@20:38:21.539575", undefined],
            ["unquotedtoken", "9223372036854775808", undefined],
            ["unquotedtoken", "123456789", undefined],
            ["unquotedtoken", "-123456789", undefined],
            ["unquotedtoken", "2147483647", undefined],
            ["unquotedtoken", "-2147483647", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "johnsmith": {
        text: '{ "firstName": "John", "lastName" : "Smith", "age" : ' +
            '25, "address" : { "streetAddress": "21 2nd Street", ' +
            '"city" : "New York", "state" : "NY", "postalCode" : ' +
            ' "10021" }, "phoneNumber": [ { "type" : "home", ' +
            '"unquotedtoken": "212 555-1234" }, { "type" : "fax", ' +
            '"unquotedtoken": "646 555-4567" } ] }',
        events: [
            ["openobject", "{", undefined],
            ["key", "firstName", undefined],
            ["quotedstring", "John", undefined],
            ["key", "lastName", undefined],
            ["quotedstring", "Smith", undefined],
            ["key", "age", undefined],
            ["unquotedtoken", "25", undefined],
            ["key", "address", undefined],
            ["openobject", "{", undefined],
            ["key", "streetAddress", undefined],
            ["quotedstring", "21 2nd Street", undefined],
            ["key", "city", undefined],
            ["quotedstring", "New York", undefined],
            ["key", "state", undefined],
            ["quotedstring", "NY", undefined],
            ["key", "postalCode", undefined],
            ["quotedstring", "10021", undefined],
            ["closeobject", "}", undefined],
            ["key", "phoneNumber", undefined],
            ["openarray", "[", undefined],
            ["openobject", "{", undefined],
            ["key", "type", undefined],
            ["quotedstring", "home", undefined],
            ["key", "unquotedtoken", undefined],
            ["quotedstring", "212 555-1234", undefined],
            ["closeobject", "}", undefined],
            ["openobject", "{", undefined],
            ["key", "type", undefined],
            ["quotedstring", "fax", undefined],
            ["key", "unquotedtoken", undefined],
            ["quotedstring", "646 555-4567", undefined],
            ["closeobject", "}", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "array null": {
        text: '[null,false,true]',
        testForLocation: true,
        chunks: [
            '[nu',
            'll,',
            'fa',
            'lse,',
            'tr',
            'ue]'],
        events: [
            ["openarray", "[", [1, 1, 1, 2]],
            ["unquotedtoken", "null", [1, 2, 1, 6]],
            ["unquotedtoken", "false", [1, 7, 1, 12]],
            ["unquotedtoken", "true", [1, 13, 1, 17]],
            ["closearray", "]", [1, 17, 1, 18]],
            ["end", [1, 18]],
        ],
    },
    "empty array comma": {
        text: '{"a":[],"c": {}, "b": true}',
        events: [
            ["openobject", "{", undefined],
            ["key", "a", undefined],
            ["openarray", "[", undefined],
            ["closearray", "]", undefined],
            ["key", "c", undefined],
            ["openobject", "{", undefined],
            ["closeobject", "}", undefined],
            ["key", "b", undefined],
            ["unquotedtoken", "true", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "incomplete json terminates ending in number": {
        text: '[[1,2,3],[42,0',
        testForLocation: true,
        events: [
            ["openarray", "[", [1, 1, 1, 2]],
            ["openarray", "[", [1, 2, 1, 3]],
            ["unquotedtoken", "1", [1, 3, 1, 4]],
            ["unquotedtoken", "2", [1, 5, 1, 6]],
            ["unquotedtoken", "3", [1, 7, 1, 8]],
            ["closearray", "]", [1, 8, 1, 9]],
            ["openarray", "[", [1, 10, 1, 11]],
            ["unquotedtoken", "42", [1, 11, 1, 13]],
            ["unquotedtoken", "0", [1, 14, 1, 15]],
            ['parsererror', 'unexpected end of document, still in nested type'],
            ["end", [1, 15]],
        ],
    },
    "incomplete json terminates ending in comma": {
        text: '[[1,2,42],',
        events: [
            ["openarray", "[", undefined],
            ["openarray", "[", undefined],
            ["unquotedtoken", "1", undefined],
            ["unquotedtoken", "2", undefined],
            ["unquotedtoken", "42", undefined],
            ["closearray", "]", undefined],
            ['parsererror', 'unexpected end of document, still in nested type'],
            ["end", undefined],
        ],
    },
    "json org": {
        text: ('{\r\n' +
            '                    "glossary": {\n' +
            '                            "title": "example glossary",\n\r' +
            '            \t\t"GlossDiv": {\r\n' +
            '                                    "title": "S",\r\n' +
            '            \t\t\t"GlossList": {\r\n' +
            '                                            "GlossEntry": {\r\n' +
            '                                                    "ID": "SGML",\r\n' +
            '            \t\t\t\t\t"SortAs": "SGML",\r\n' +
            '            \t\t\t\t\t"GlossTerm": "Standard Generalized ' +
            'Markup Language",\r\n' +
            '            \t\t\t\t\t"Acronym": "SGML",\r\n' +
            '            \t\t\t\t\t"Abbrev": "ISO 8879:1986",\r\n' +
            '            \t\t\t\t\t"GlossDef": {\r\n' +
            '                                                            "para": "A meta-markup language,' +
            ' used to create markup languages such as DocBook.",\r\n' +
            '            \t\t\t\t\t\t"GlossSeeAlso": ["GML", "XML"]\r\n' +
            '                                                    },\r\n' +
            '            \t\t\t\t\t"GlossSee": "markup"\r\n' +
            '                                            }\r\n' +
            '                                    }\r\n' +
            '                            }\r\n' +
            '                    }\r\n' +
            '            }\r\n'),
        skipRoundTripCheck: true,
        events: [
            ["openobject", "{", undefined],
            ["key", "glossary", undefined],
            ["openobject", "{", undefined],
            ["key", "title", undefined],
            ["quotedstring", "example glossary", undefined],
            ["key", "GlossDiv", undefined],
            ["openobject", "{", undefined],
            ["key", "title", undefined],
            ["quotedstring", "S", undefined],
            ["key", "GlossList", undefined],
            ["openobject", "{", undefined],
            ["key", "GlossEntry", undefined],
            ["openobject", "{", undefined],
            ["key", "ID", undefined],
            ["quotedstring", "SGML", undefined],
            ["key", "SortAs", undefined],
            ["quotedstring", "SGML", undefined],
            ["key", "GlossTerm", undefined],
            ["quotedstring", "Standard Generalized Markup Language", undefined],
            ["key", "Acronym", undefined],
            ["quotedstring", "SGML", undefined],
            ["key", "Abbrev", undefined],
            ["quotedstring", 'ISO 8879:1986', undefined],
            ["key", "GlossDef", undefined],
            ["openobject", "{", undefined],
            ["key", "para", undefined],
            ["quotedstring", 'A meta-markup language, used to create markup languages such as DocBook.', undefined],
            ["key", "GlossSeeAlso", undefined],
            ["openarray", "[", undefined],
            ["quotedstring", "GML", undefined],
            ["quotedstring", "XML", undefined],
            ["closearray", "]", undefined],
            ["closeobject", "}", undefined],
            ["key", "GlossSee", undefined],
            ["quotedstring", "markup", undefined],
            ["closeobject", "}", undefined],
            ["closeobject", "}", undefined],
            ["closeobject", "}", undefined],
            ["closeobject", "}", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
    "string chunk span": {
        text: '["L\'OrÃ©al", "LÃ©\'Oral", "Ã©alL\'Or"]',
        chunks: [
            '["L\'OrÃ',
            '©al", "LÃ©\'Oral", "Ã©alL\'Or"]'],
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", 'L\'OrÃ©al', undefined],
            ["quotedstring", 'LÃ©\'Oral', undefined],
            ["quotedstring", 'Ã©alL\'Or', undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension apostrophe string": {
        text: "'a string'",
        events: [
            ["validationerror", "invalid string, should start with'\"'"],
            ["quotedstring", "a string", undefined],
            ["end", undefined],
        ],
    },
    "multiline string": {
        text: '["a\nstring"]',
        skipRoundTripCheck: true,
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", "a\nstring", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension trailing comma": {
        text: '[1,2,]',
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "1", undefined],
            ["unquotedtoken", "2", undefined],
            ["validationerror", "trailing commas are not allowed"],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension block comment": {
        text: '[1,2/*a comment\r\n*/]',
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "1", undefined],
            ["unquotedtoken", "2", undefined],
            ["validationerror", "block comments are not allowed in strict JSON"],
            ["blockcomment", "a comment\r\n", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension parens instead of braces": {
        text: '( "a": "foo" )',
        events: [
            ["validationerror", "objects should start with '{' in strict JSON"],
            ["openobject", "(", undefined],
            ["key", "a", undefined],
            ["quotedstring", "foo", undefined],
            ["validationerror", "objects should end with '}' in strict JSON"],
            ["closeobject", ")", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension missing comma": {
        text: '["foo""bar"]',
        events: [
            ["openarray", "[", undefined],
            ["quotedstring", "foo", undefined],
            ["validationerror", "expected comma or array end"],
            ["quotedstring", "bar", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension angle brackets instead of brackets": {
        text: '<"foo">',
        events: [
            ["validationerror", "arrays should start with '[' in strict JSON"],
            ["openarray", "<", undefined],
            ["quotedstring", "foo", undefined],
            ["validationerror", "arrays should end with ']' in strict JSON"],
            ["closearray", ">", undefined],
            ["end", undefined],
        ],
    },
    "forbidden extension single line comment": {
        text: '[1,2//a comment\r\n]',
        skipRoundTripCheck: true,
        events: [
            ["openarray", "[", undefined],
            ["unquotedtoken", "1", undefined],
            ["unquotedtoken", "2", undefined],
            ["validationerror", "line comments are not allowed in strict JSON"],
            ["linecomment", "a comment", undefined],
            ["closearray", "]", undefined],
            ["end", undefined],
        ],
    },
    "forbidden tagged union": {
        text: '| "foo" "x"',
        events: [
            ["validationerror", "tagged unions are not allowed in strict JSON"],
            ["opentaggedunion", undefined],
            ["option", "foo", undefined],
            ["quotedstring", "x", undefined],
            ["closetaggedunion"],
            ["end", undefined],
        ],
    },
    "forbidden schema": {
        text: '! "foo" {}',
        testHeaders: true,
        events: [
            ["headerstart"],
            ["validationerror", "headers are not allowed in strict JSON"],
            ["quotedstring", "foo", undefined],
            ["headerend"],
            ["openobject", "{", undefined],
            ["closeobject", "}", undefined],
            ["end", undefined],
        ],
    },
}
